# Generated by Django 6.0.3 on 2026-06-16 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0004_movimentacaoestoque'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='documento',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='fornecedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='almoxarifado.fornecedor'),
        ),
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='responsavel',
            field=models.CharField(default='Administrador', max_length=100),
            preserve_default=False,
        ),
    ]
