# Generated by Django 6.0.3 on 2026-06-16 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0005_movimentacaoestoque_documento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacaoestoque',
            name='responsavel',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
