# Generated by Django 6.0.3 on 2026-07-03 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0007_setor_alter_categoria_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['nome'], 'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='fornecedor',
            options={'ordering': ['razao_social'], 'verbose_name': 'Fornecedor', 'verbose_name_plural': 'Fornecedores'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['descricao'], 'verbose_name': 'Item', 'verbose_name_plural': 'Itens'},
        ),
        migrations.AlterModelOptions(
            name='movimentacaoestoque',
            options={'ordering': ['-data_movimentacao'], 'verbose_name': 'Movimentação de Estoque', 'verbose_name_plural': 'Movimentações de Estoque'},
        ),
        migrations.CreateModel(
            name='ServidorAlmoxarifado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('matricula', models.CharField(max_length=30, unique=True)),
                ('cargo', models.CharField(max_length=100)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('ativo', models.BooleanField(default=True)),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='almoxarifado.setor')),
            ],
            options={
                'verbose_name': 'Servidor do Almoxarifado',
                'verbose_name_plural': 'Servidores do Almoxarifado',
                'ordering': ['nome'],
            },
        ),
    ]
