# Generated by Django 6.0.3 on 2026-07-06 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0008_alter_categoria_options_alter_fornecedor_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('SA', 'Setor Administrativo'), ('UP', 'Unidade Prisional'), ('OU', 'Outro')], max_length=2)),
                ('nome', models.CharField(max_length=150, unique=True)),
                ('cidade', models.CharField(blank=True, max_length=100)),
                ('responsavel', models.CharField(blank=True, max_length=150)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Destino',
                'verbose_name_plural': 'Destinos',
                'ordering': ['nome'],
            },
        ),
    ]
