# Generated by Django 6.0.3 on 2026-07-08 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0009_destino'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='almoxarifado.destino'),
        ),
    ]
