# Generated by Django 6.0.3 on 2026-07-08 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0010_movimentacaoestoque_destino'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacaoestoque',
            name='destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='almoxarifado.destino', verbose_name='Destino'),
        ),
    ]
