# Generated by Django 6.0.3 on 2026-07-09 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0011_alter_movimentacaoestoque_destino'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requisicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('data_requisicao', models.DateTimeField(auto_now_add=True)),
                ('solicitante', models.CharField(max_length=150)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('observacao', models.TextField(blank=True)),
                ('data_atendimento', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SOLICITADA', 'Solicitada'), ('SEPARACAO', 'Em Separação'), ('ATENDIDA', 'Atendida'), ('CANCELADA', 'Cancelada')], default='SOLICITADA', max_length=20)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requisicoes', to='almoxarifado.destino')),
                ('servidor_almoxarifado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='almoxarifado.servidoralmoxarifado')),
            ],
            options={
                'verbose_name': 'Requisição',
                'verbose_name_plural': 'Requisições',
                'ordering': ['-data_requisicao'],
            },
        ),
    ]
