# Generated by Django 6.0.3 on 2026-07-10 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0012_requisicao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisicao',
            name='destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requisicoes', to='almoxarifado.destino', verbose_name='Destino'),
        ),
        migrations.AlterField(
            model_name='requisicao',
            name='servidor_almoxarifado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requisicoes_atendidas', to='almoxarifado.servidoralmoxarifado'),
        ),
    ]
