# Generated by Django 6.0.3 on 2026-07-10 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0013_alter_requisicao_destino_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemRequisicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_solicitada', models.PositiveIntegerField()),
                ('quantidade_atendida', models.PositiveIntegerField(default=0)),
                ('observacao', models.CharField(blank=True, max_length=255)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='almoxarifado.item')),
                ('requisicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='almoxarifado.requisicao')),
            ],
            options={
                'verbose_name': 'Item da Requisição',
                'verbose_name_plural': 'Itens da Requisição',
                'ordering': ['id'],
            },
        ),
    ]
